In [ ]:
import numpy as np

x = np.array([1, 2, 3], np.int16)  # Create 1-dim array  
print(x)
print(type(x))

In [6]:
x[0], x[1]

(1, 2)

In [7]:
x = np.array([[1, 2, 3],[4,5,6]], np.int16)  # Create 2-dim array  
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [18]:
print(x)
print(x[1][1]) # 1st array 1st element 
print(x[0,2])  # 0th row 2nd column one value
print(x[:,1])  # all from 1st column as a row
print(x[:,0])  # all from 0th column as a row
print(x[:,2])  # all from 2nd column as a row

print(x[0,:])  # all from 0th row as a row
print(x[1,:])  # all from 1st row as a row

[[1 2 3]
 [4 5 6]]
5
3
[2 5]
[1 4]
[3 6]
[1 2 3]
[4 5 6]


## Properties

In [26]:
print(x.shape)  # 2-dim array
print(x.ndim)   # 2
print(x.dtype)  # int 16 data type of nd array
print(x.size)   # Total elements in the array here its 6
print(x.nbytes) # 12  size in bytes

(2, 3)
2
int16
6
12


In [27]:
print(x.T)  # Get the transpose of the array

[[1 4]
 [2 5]
 [3 6]]


## Constants

In [29]:
print(np.inf)    # +ve infinity
print(np.NAN)    # not a number
print(np.NINF)   # -ve infinity
print(np.NZERO)  # -ve zeros
print(np.PZERO)  # +ve zeros

print(np.e)  # 2.718281828459045
print(np.euler_gamma)  # 0.5772156649015329
print(np.pi)  # 3.141592653589793

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793
