In [6]:
import cv2


img = cv2.imread("images/tree.jpeg")
print(type(img))
print(img)
cv2.imshow('Tree', img)
cv2.waitKey(3000)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[[ 7 16  6]
  [11 20 10]
  [16 25 15]
  ...
  [ 1  0  2]
  [ 1  0  2]
  [ 1  0  2]]

 [[ 3 11  1]
  [ 2 11  1]
  [ 3 12  2]
  ...
  [ 1  0  2]
  [ 1  0  2]
  [ 1  0  2]]

 [[ 2  6  0]
  [ 0  4  0]
  [ 0  3  0]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 ...

 [[ 5  8  6]
  [ 0  1  0]
  [ 0  2  0]
  ...
  [23 29 24]
  [22 28 23]
  [15 21 16]]

 [[ 5  8  6]
  [ 0  1  0]
  [ 0  2  0]
  ...
  [20 26 21]
  [15 21 16]
  [10 16 11]]

 [[ 6  9  7]
  [ 0  1  0]
  [ 0  3  1]
  ...
  [11 17 12]
  [11 17 12]
  [13 19 14]]]


In [8]:
img_gray = cv2.imread("images/tree.jpeg", 0)
print(img_gray)
cv2.imshow('Gray Tree', img)
cv2.waitKey(3000)
cv2.destroyAllWindows()

[[12 16 21 ...  1  1  1]
 [ 7  7  8 ...  1  1  1]
 [ 4  1  0 ...  1  1  1]
 ...
 [ 7  0  1 ... 27 26 19]
 [ 7  0  1 ... 24 19 14]
 [ 8  0  2 ... 15 15 17]]


In [9]:
cv2.imwrite("cv2_output.jpg", img_gray)

True

In [15]:
import numpy as np

canvas_image = np.zeros((512, 512))
print(canvas_image)
cv2.imshow('Canvas Image', canvas_image)
cv2.waitKey(2000)
cv2.destroyWindow("Canvas Image")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## WebCam